version: "3.1"

services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "adminpass"
      POSTGRES_DB: "main"
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@capicloud.io"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - "80:80"