[tool.poetry]
<<<<<<< HEAD
name = "api-capi-zip-develop"
version = "2"
description = "encurtador de link"
authors = ["Carlos Miguel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
sqlalchemy = "^2.0.23"
alembic = "^1.12.1"
python-decouple = "^3.8"
passlib = "^1.7.4"
python-jose = "^3.3.0"
python-multipart = "^0.0.6"
psycopg2-binary = "^2.9.9"
=======
name = "api-capi-zip"
version = "0.1.0"
description = ""
authors = ["Aristeu <aristeuneto13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<=3.13"
fastapi = "^0.104.0"
pydantic-settings = "^2.0.3"
>>>>>>> 7460434a6a0601a56eac8a201d9257c754c49816


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
