"""k

Revision ID: 2b94c7aa8aee
Revises: 307241fa6e52
Create Date: 2024-03-22 18:17:05.543661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b94c7aa8aee'
down_revision: Union[str, None] = '307241fa6e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('link_short_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('localization', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['link_short_id'], ['link_short.short_link'], name='click_link_short_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_short_id', name='click_pkey')
    )
    # ### end Alembic commands ###
