"""mudance table click

Revision ID: 55e3a13ce9fa
Revises: 38d48c01fdc2
Create Date: 2024-02-24 12:07:03.898808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e3a13ce9fa'
down_revision: Union[str, None] = '38d48c01fdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('user_agent', sa.String(), nullable=False))
    op.drop_column('click', 'user_agend')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('user_agend', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('click', 'user_agent')
    # ### end Alembic commands ###
