""" add new password  reset_password 

Revision ID: 58c46e1265e3
Revises: 470e37fb172f
Create Date: 2023-11-30 16:17:33.083323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c46e1265e3'
down_revision: Union[str, None] = '470e37fb172f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_password', sa.Column('new_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reset_password', 'new_password')
    # ### end Alembic commands ###
