"""add id table click

Revision ID: 74220bba0667
Revises: 9402c9214fe3
Create Date: 2024-03-22 17:55:32.306247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74220bba0667'
down_revision: Union[str, None] = '9402c9214fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('click_link_short_id_fkey', 'click', type_='foreignkey')
    op.create_foreign_key(None, 'click', 'link_short', ['link_short_id'], ['short_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'click', type_='foreignkey')
    op.create_foreign_key('click_link_short_id_fkey', 'click', 'link_short', ['link_short_id'], ['short_link'], ondelete='CASCADE')
    # ### end Alembic commands ###
