"""mudance table click

Revision ID: 9402c9214fe3
Revises: 1dec33f50194
Create Date: 2024-02-24 12:59:43.788329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9402c9214fe3'
down_revision: Union[str, None] = '1dec33f50194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('click_link_short_id_key', 'click', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('click_link_short_id_key', 'click', ['link_short_id'])
    op.drop_column('click', 'id')
    # ### end Alembic commands ###
