"""add 2 table click

Revision ID: b249ce87361d
Revises: 89cd2751221d
Create Date: 2024-03-22 18:19:12.348964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b249ce87361d'
down_revision: Union[str, None] = '89cd2751221d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_short_id', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('localization', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['link_short_id'], ['link_short.short_link'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    # ### end Alembic commands ###
