"""add atribute created_at  table reset_password

Revision ID: ba347bb81f06
Revises: ec552862760d
Create Date: 2024-04-05 22:29:42.041696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba347bb81f06'
down_revision: Union[str, None] = 'ec552862760d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_password', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reset_password', 'created_at')
    # ### end Alembic commands ###
