"""change table click

Revision ID: bf42cd6851cd
Revises: 74220bba0667
Create Date: 2024-03-22 18:11:05.645736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf42cd6851cd'
down_revision: Union[str, None] = '74220bba0667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('click_link_short_id_fkey', 'click', type_='foreignkey')
    op.create_foreign_key(None, 'click', 'link_short', ['link_short_id'], ['short_link'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'click', type_='foreignkey')
    op.create_foreign_key('click_link_short_id_fkey', 'click', 'link_short', ['link_short_id'], ['short_link'])
    # ### end Alembic commands ###
